# Generated by Django 3.1 on 2021-06-05 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210605_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
